const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Exps.min,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{bar_bg_progress: 0},
	{bgBoosterMenu: 0},
	{bgNumberBooster: 0},
	{powerup: 0},
	{btnBusterButton: 0},
	{btnPlay: 0},
	{btnSettings: 0},
	{logo: 0},
	{lupa_big: 0},
	{lupa_small: 0},
	{play_icon: 0},
	{progress_pin_menu: 0},
	{reloj_big: 0},
	{reloj_small: 0},
	{name: 0},
	{txtMenuScore: 0},
	{your_score_menu: 0},
	{bar_progress: 0},
	{bar_bg_volume: 0},
	{bgSettings: 0},
	{bgVolumeSettings: 0},
	{btnClose: 0},
	{btnFX: 0},
	{btnSound: 0},
	{btnMoreGames: 0},
	{line: 0},
	{btnVolume: 0},
	{settings_title: 0},
	{volume_bar: 0},
	{transition: 0},
	{fade: 0},
	{bg: 0},
	{bgUITop: 0},
	{iconClockUI: 0},
	{iconNoteUI: 0},
	{startw: 0},
	{time_bar: 0},
	{bgUIBottom: 0},
	{txtUI: 0},
	{Tween: 0},
	{txtFraseIG: 0},
	{objectname: 0},
	{unlocked: 0},
	{size: 0},
	{Artboard: 0},
	{Artboard10: 0},
	{Artboard11: 0},
	{Artboard12: 0},
	{Artboard13: 0},
	{Artboard14: 0},
	{Artboard15: 0},
	{Artboard16: 0},
	{Artboard17: 0},
	{Artboard18: 0},
	{Artboard19: 0},
	{Artboard2: 0},
	{Artboard20: 0},
	{Artboard21: 0},
	{Artboard22: 0},
	{Artboard23: 0},
	{Artboard24: 0},
	{Artboard25: 0},
	{Artboard26: 0},
	{Artboard26Copy: 0},
	{Artboard27: 0},
	{Artboard28: 0},
	{Artboard29: 0},
	{Artboard3: 0},
	{Artboard30: 0},
	{Artboard31: 0},
	{Artboard32: 0},
	{Artboard33: 0},
	{Artboard34: 0},
	{Artboard35: 0},
	{Artboard36: 0},
	{Artboard37: 0},
	{Artboard38: 0},
	{Artboard38Copy: 0},
	{Artboard38Copy2: 0},
	{Artboard39: 0},
	{Artboard4: 0},
	{Artboard40: 0},
	{Artboard41: 0},
	{Artboard42: 0},
	{Artboard43: 0},
	{Artboard44: 0},
	{Artboard45: 0},
	{Artboard46: 0},
	{Artboard47: 0},
	{Artboard48: 0},
	{Artboard49: 0},
	{Artboard5: 0},
	{Artboard50: 0},
	{Artboard51: 0},
	{Artboard52: 0},
	{Artboard53: 0},
	{Artboard54: 0},
	{Artboard55: 0},
	{Artboard56: 0},
	{Artboard57: 0},
	{Artboard58: 0},
	{Artboard59: 0},
	{Artboard6: 0},
	{Artboard60: 0},
	{Artboard60Copy: 0},
	{Artboard61: 0},
	{Artboard62: 0},
	{Artboard63: 0},
	{Artboard64: 0},
	{Artboard65: 0},
	{Artboard66: 0},
	{Artboard67: 0},
	{Artboard68: 0},
	{Artboard69: 0},
	{Artboard7: 0},
	{Artboard70: 0},
	{Artboard71: 0},
	{Artboard8: 0},
	{Artboard9: 0},
	{fade_bottom: 0},
	{fade_top: 0},
	{DragDrop: 0},
	{Bullet: 0},
	{Panel: 0},
	{defeat: 0},
	{win: 0},
	{totaltime: 0},
	{currenttime: 0},
	{totobjects: 0},
	{currentobjects: 0},
	{object: 0},
	{game_manager: 0},
	{Touch: 0},
	{Mouse: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Audio: 0},
	{Variables: 0},
	{bgDefeat: 0},
	{btnUseClockDefeat: 0},
	{btnWatchVide: 0},
	{defeat_logo: 0},
	{bgWin: 0},
	{btnContinue: 0},
	{Sine: 0},
	{Stuff: 0},
	{Buttons: 0},
	{padding: 0},
	{newX: 0},
	{newY: 0},
	{oldX: 0},
	{oldY: 0},
	{stufID: 0},
	{posX: 0},
	{posY: 0},
	{newText: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newLayer: 0},
	{GAMENAME_SAVE: 0},
	{TOTALXP: 0},
	{SOUNDVOLUME: 0}
];

self.InstanceType = {
	bar_bg_progress: class extends self.ISpriteInstance {},
	bgBoosterMenu: class extends self.ISpriteInstance {},
	bgNumberBooster: class extends self.ISpriteInstance {},
	btnBusterButton: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnSettings: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	lupa_big: class extends self.ISpriteInstance {},
	lupa_small: class extends self.ISpriteInstance {},
	play_icon: class extends self.ISpriteInstance {},
	progress_pin_menu: class extends self.ISpriteInstance {},
	reloj_big: class extends self.ISpriteInstance {},
	reloj_small: class extends self.ISpriteInstance {},
	txtMenuScore: class extends self.ISpriteFontInstance {},
	your_score_menu: class extends self.ISpriteInstance {},
	bar_progress: class extends self.ITiledBackgroundInstance {},
	bar_bg_volume: class extends self.ISpriteInstance {},
	bgSettings: class extends self.ISpriteInstance {},
	bgVolumeSettings: class extends self.ISpriteInstance {},
	btnClose: class extends self.ISpriteInstance {},
	btnFX: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	btnMoreGames: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	btnVolume: class extends self.ISpriteInstance {},
	settings_title: class extends self.ISpriteInstance {},
	volume_bar: class extends self.ITiledBackgroundInstance {},
	transition: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	bgUITop: class extends self.ISpriteInstance {},
	iconClockUI: class extends self.ISpriteInstance {},
	iconNoteUI: class extends self.ISpriteInstance {},
	time_bar: class extends self.ITiledBackgroundInstance {},
	bgUIBottom: class extends self.ISpriteInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	txtFraseIG: class extends self.ISpriteFontInstance {},
	Artboard: class extends self.ISpriteInstance {},
	Artboard10: class extends self.ISpriteInstance {},
	Artboard11: class extends self.ISpriteInstance {},
	Artboard12: class extends self.ISpriteInstance {},
	Artboard13: class extends self.ISpriteInstance {},
	Artboard14: class extends self.ISpriteInstance {},
	Artboard15: class extends self.ISpriteInstance {},
	Artboard16: class extends self.ISpriteInstance {},
	Artboard17: class extends self.ISpriteInstance {},
	Artboard18: class extends self.ISpriteInstance {},
	Artboard19: class extends self.ISpriteInstance {},
	Artboard2: class extends self.ISpriteInstance {},
	Artboard20: class extends self.ISpriteInstance {},
	Artboard21: class extends self.ISpriteInstance {},
	Artboard22: class extends self.ISpriteInstance {},
	Artboard23: class extends self.ISpriteInstance {},
	Artboard24: class extends self.ISpriteInstance {},
	Artboard25: class extends self.ISpriteInstance {},
	Artboard26: class extends self.ISpriteInstance {},
	Artboard26Copy: class extends self.ISpriteInstance {},
	Artboard27: class extends self.ISpriteInstance {},
	Artboard28: class extends self.ISpriteInstance {},
	Artboard29: class extends self.ISpriteInstance {},
	Artboard3: class extends self.ISpriteInstance {},
	Artboard30: class extends self.ISpriteInstance {},
	Artboard31: class extends self.ISpriteInstance {},
	Artboard32: class extends self.ISpriteInstance {},
	Artboard33: class extends self.ISpriteInstance {},
	Artboard34: class extends self.ISpriteInstance {},
	Artboard35: class extends self.ISpriteInstance {},
	Artboard36: class extends self.ISpriteInstance {},
	Artboard37: class extends self.ISpriteInstance {},
	Artboard38: class extends self.ISpriteInstance {},
	Artboard38Copy: class extends self.ISpriteInstance {},
	Artboard38Copy2: class extends self.ISpriteInstance {},
	Artboard39: class extends self.ISpriteInstance {},
	Artboard4: class extends self.ISpriteInstance {},
	Artboard40: class extends self.ISpriteInstance {},
	Artboard41: class extends self.ISpriteInstance {},
	Artboard42: class extends self.ISpriteInstance {},
	Artboard43: class extends self.ISpriteInstance {},
	Artboard44: class extends self.ISpriteInstance {},
	Artboard45: class extends self.ISpriteInstance {},
	Artboard46: class extends self.ISpriteInstance {},
	Artboard47: class extends self.ISpriteInstance {},
	Artboard48: class extends self.ISpriteInstance {},
	Artboard49: class extends self.ISpriteInstance {},
	Artboard5: class extends self.ISpriteInstance {},
	Artboard50: class extends self.ISpriteInstance {},
	Artboard51: class extends self.ISpriteInstance {},
	Artboard52: class extends self.ISpriteInstance {},
	Artboard53: class extends self.ISpriteInstance {},
	Artboard54: class extends self.ISpriteInstance {},
	Artboard55: class extends self.ISpriteInstance {},
	Artboard56: class extends self.ISpriteInstance {},
	Artboard57: class extends self.ISpriteInstance {},
	Artboard58: class extends self.ISpriteInstance {},
	Artboard59: class extends self.ISpriteInstance {},
	Artboard6: class extends self.ISpriteInstance {},
	Artboard60: class extends self.ISpriteInstance {},
	Artboard60Copy: class extends self.ISpriteInstance {},
	Artboard61: class extends self.ISpriteInstance {},
	Artboard62: class extends self.ISpriteInstance {},
	Artboard63: class extends self.ISpriteInstance {},
	Artboard64: class extends self.ISpriteInstance {},
	Artboard65: class extends self.ISpriteInstance {},
	Artboard66: class extends self.ISpriteInstance {},
	Artboard67: class extends self.ISpriteInstance {},
	Artboard68: class extends self.ISpriteInstance {},
	Artboard69: class extends self.ISpriteInstance {},
	Artboard7: class extends self.ISpriteInstance {},
	Artboard70: class extends self.ISpriteInstance {},
	Artboard71: class extends self.ISpriteInstance {},
	Artboard8: class extends self.ISpriteInstance {},
	Artboard9: class extends self.ISpriteInstance {},
	fade_bottom: class extends self.ISpriteInstance {},
	fade_top: class extends self.ISpriteInstance {},
	Panel: class extends self.ITiledBackgroundInstance {},
	game_manager: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Variables: class extends self.IArrayInstance {},
	bgDefeat: class extends self.ISpriteInstance {},
	btnUseClockDefeat: class extends self.ISpriteInstance {},
	btnWatchVide: class extends self.ISpriteInstance {},
	defeat_logo: class extends self.ISpriteInstance {},
	bgWin: class extends self.ISpriteInstance {},
	btnContinue: class extends self.ISpriteInstance {},
	Stuff: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}